# Generated by Django 4.0.5 on 2022-07-05 15:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=255)),
                ('cell_phone', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('country_of_birth', models.CharField(max_length=255)),
                ('country_issuing_passport', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('israeli_citizenship', models.BooleanField()),
                ('israeli_passport', models.BooleanField()),
                ('current_school', models.CharField(max_length=255)),
                ('synagogue', models.CharField(max_length=255)),
                ('high_school_transcripts', models.FileField(upload_to=api.models.user_directory_path)),
                ('photo', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to=api.models.user_directory_path)),
            ],
        ),
        migrations.DeleteModel(
            name='DisclosureAgreement',
        ),
        migrations.DeleteModel(
            name='HealthForm',
        ),
    ]
